spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000 #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
      max-active: 50 #连接池的最大数据库连接数。设为0表示无限制。
      test-on-borrow: true
      validation-query: SELECT 1
      max-idle: 100 #最大空闲数，数据库连接的最大空闲时间。默认100
      min-idle: 10 #最大空闲数，数据库连接的最大空闲时间。默认10
  jpa:
    show-sql: true
  profiles:
    active: @spring.profile@
---
spring:
  profiles: dev
server:
  port: 8001
spring.datasource.password: mysql
---
spring:
  profiles: prod
server:
  port: 8002
spring.datasource.password: MyNewPass4!
