spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8001

---
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    tomcat.max-wait: 10000
    tomcat.max-active: 50
    tomcat.test-on-borrow: true
  jpa:
    show-sql: true
server:
  port: 8002

